// cards.js
// Centralized card and rank definitions

export const RANKS = {
  C: { name: "C", color: 0x00A300, icon: "https://files.catbox.moe/8gn79p.png", value: 1 },
  B: { name: "B", color: 0x3498db, icon: "https://files.catbox.moe/rv1frd.png", value: 2 },
  A: { name: "A", color: 0x9b59b6, icon: "https://files.catbox.moe/ussec9.webp", value: 3 },
  S: { name: "S", color: 0xe74c3c, icon: "https://files.catbox.moe/wrx7hl.png", value: 4 },
  SS: { name: "SS", color: 0xFF8C00, icon: null, value: 5 }, // dark orange
  UR: { name: "UR", color: 0x8B0000, icon: null, value: 6 }, // dark red
};

export const cards = [
  {
    id: "luffy_b_01",
    name: "Monkey D. Luffy",
    title: "The man of freedom",
    rank: "B",
    power: 60,
    attackRange: [16, 24],
    health: 140,
    type: "Attack",
    ability: "Gambling rewards +10%",
    image: "https://files.catbox.moe/24a5fq.jpg",
    evolutions: ["luffy_a_02"],
  },
  {
    id: "luffy_a_02",
    name: "Monkey D. Luffy",
    title: "Captain of the Strawhat Pirates",
    rank: "A",
    power: 160,
    attackRange: [26, 44],
    health: 210,
    type: "Attack",
    ability: "Gambling rewards +20%",
    image: "https://files.catbox.moe/hkxjpn.jpg",
    evolutions: ["luffy_s_03"],
    isUpgrade: true,
    upgradeRequirements: { cost: 2000, minLevel: 20 },
  },
  {
    id: "luffy_s_03",
    name: "Monkey D. Luffy",
    title: "Worst generation pirate",
    rank: "S",
    power: 300,
    attackRange: [30, 70],
    health: 310,
    type: "Attack",
    ability: "Gambling rewards +30%",
    image: "https://files.catbox.moe/l6s82l.jpg",
    evolutions: ["luffy_ur_04"],
    isUpgrade: true,
    upgradeRequirements: { cost: 5000, minLevel: 35 },
  },
  {
    id: "shanks_s_01",
    name: "Shanks",
    title: "Captain of the Red-Haired pirates",
    rank: "S",
    power: 300,
    attackRange: [30, 60],
    health: 300,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/d7vn4a.jpg",
    evolutions: ["shanks_ur_02"],
  },
  // New additions
  {
    id: "luffy_ur_04",
    name: "Monkey D. Luffy",
    title: "The Warrior of Liberation",
    rank: "UR",
    power: 1150,
    attackRange: [120, 170],
    health: 780,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/ppdc69.jpg", // placeholder
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 100000, minLevel: 100 },
  },
  {
    id: "shanks_ur_02",
    name: "Shanks",
    title: "Emperor of the New Era",
    rank: "UR",
    power: 1000,
    attackRange: [100, 150],
    health: 700,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/7iqdjj.jpg", // placeholder
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 30000, minLevel: 75 },
  },
  {
    id: "zoro_b_01",
    name: "Roronoa Zoro",
    title: "Moss head",
    rank: "B",
    power: 70,
    attackRange: [20, 30],
    health: 140,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/xsiawi.jpg",
    evolutions: ["zoro_s_02"],
  },
  {
    id: "zoro_s_02",
    name: "Roronoa Zoro",
    title: "Pirate hunter",
    rank: "S",
    power: 200,
    attackRange: [30, 50],
    health: 250,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/ln2a8x.jpg",
    evolutions: ["zoro_ss_03"],
    isUpgrade: true,
    upgradeRequirements: { cost: 7500, minLevel: 40 },
  },
  {
    id: "zoro_ss_03",
    name: "Roronoa Zoro",
    title: "King of hell",
    rank: "SS",
    power: 350,
    attackRange: [60, 100],
    health: 350,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/z02f87.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 20000, minLevel: 60 },
  },
  {
    id: "beckman_a_01",
    name: "Benn Beckman",
    title: "First Mate of the Red-Haired pirates",
    rank: "A",
    power: 180,
    attackRange: [25, 38],
    health: 215,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/0xnjto.jpg",
    evolutions: ["beckman_s_02"],
  },
  {
    id: "beckman_s_02",
    name: "Benn Beckman",
    title: "High-Ranking Yonko Commander",
    rank: "S",
    power: 226,
    attackRange: [33, 62],
    health: 240,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/12j3d0.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 7500, minLevel: 40 },
  },
  // Added new cards requested by user
  {
    id: "yasopp_a_01",
    name: "Yasopp",
    title: "Sniper of the Red-Haired Pirates",
    rank: "A",
    power: 140,
    attackRange: [30, 45],
    health: 200,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/qua2du.jpg",
    evolutions: ["yasopp_s_02"],
  },
  {
    id: "yasopp_s_02",
    name: "Yasopp",
    title: "Veteran Sniper (Red-Haired Pirates)",
    rank: "S",
    power: 280,
    attackRange: [40, 60],
    health: 320,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/qua2du.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 8000, minLevel: 40 },
  },
  {
    id: "luckyroux_a_01",
    name: "Lucky Roux",
    title: "Cook of the Big Mom Pirates",
    rank: "A",
    power: 130,
    attackRange: [28, 44],
    health: 190,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/k6rx74.jpg",
    evolutions: ["luckyroux_s_02"],
  },
  {
    id: "luckyroux_s_02",
    name: "Lucky Roux",
    title: "Senior Cook (Big Mom Pirates)",
    rank: "S",
    power: 240,
    attackRange: [35, 58],
    health: 270,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/ajdo0l.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 7000, minLevel: 35 },
  },
  {
    id: "bonkpunch_b_01",
    name: "Bonk Punch",
    title: "Minor pirate (East Blue)",
    rank: "B",
    power: 85,
    attackRange: [12, 28],
    health: 150,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/g6llhp.jpg",
    evolutions: [],
  },
  {
    id: "hongo_a_01",
    name: "Hongo",
    title: "East Blue villager",
    rank: "A",
    power: 120,
    attackRange: [22, 40],
    health: 170,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/pbdxil.jpg",
    evolutions: [],
  },
  {
    id: "limejuice_b_01",
    name: "Limejuice",
    title: "East Blue pirate",
    rank: "B",
    power: 65,
    attackRange: [14, 26],
    health: 130,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/7pfkc8.jpg",
    evolutions: [],
  },
  {
    id: "higuma_c_01",
    name: "Higuma",
    title: "Mountain bandit (East Blue)",
    rank: "C",
    power: 35,
    attackRange: [6, 14],
    health: 80,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/lz20b8.jpg",
    evolutions: [],
  },
  {
    id: "axehandmorgan_b_01",
    name: "Axe-Hand Morgan",
    title: "Marine Captain (Shells Town)",
    rank: "B",
    power: 90,
    attackRange: [18, 32],
    health: 160,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/6ekgio.jpg",
    evolutions: [],
  },
  {
    id: "helmeppo_c_01",
    name: "Helmeppo",
    title: "Young Marine (Shells Town)",
    rank: "C",
    power: 30,
    attackRange: [5, 18],
    health: 90,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/14gwtu.jpg",
    evolutions: ["helmeppo_b_02"],
  },
  {
    id: "helmeppo_b_02",
    name: "Helmeppo",
    title: "Marine Officer (Shells Town)",
    rank: "B",
    power: 70,
    attackRange: [12, 26],
    health: 140,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/s3xo09.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 1500, minLevel: 12 },
  },
  {
    id: "makino_c_01",
    name: "Makino",
    title: "Bar owner (Foosha Village)",
    rank: "C",
    power: 25,
    attackRange: [4, 12],
    health: 95,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/tpt7jn.jpg",
    evolutions: [],
  },
  {
    id: "woopslap_c_01",
    name: "Woopslap",
    title: "Minor character (East Blue)",
    rank: "C",
    power: 18,
    attackRange: [3, 10],
    health: 70,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/af46mj.webp",
    evolutions: [],
  },
  {
    id: "koby_c_01",
    name: "Koby",
    title: "Marine cabin boy",
    rank: "C",
    power: 20,
    attackRange: [4, 12],
    health: 90,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/bf4ien.jpg",
    evolutions: ["koby_a_02"],
  },
  {
    id: "koby_a_02",
    name: "Koby",
    title: "Marine officer",
    rank: "A",
    power: 155,
    attackRange: [28, 46],
    health: 200,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/qiwx5c.jpg",
    evolutions: ["koby_ss_03"],
    isUpgrade: true,
    upgradeRequirements: { cost: 6000, minLevel: 30 },
  },
  {
    id: "koby_ss_03",
    name: "Koby",
    title: "High-Ranking Marine Officer",
    rank: "SS",
    power: 320,
    attackRange: [60, 95],
    health: 360,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/telef9.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 20000, minLevel: 60 },
  },
  {
    id: "alvida_c_01",
    name: "Alvida",
    title: "Pirate captain (Alvida Crew)",
    rank: "C",
    power: 40,
    attackRange: [6, 18],
    health: 100,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/173rr8.jpg",
    evolutions: ["alvida_a_02"],
  },
  {
    id: "alvida_a_02",
    name: "Alvida",
    title: "Refined Pirate Captain",
    rank: "A",
    power: 130,
    attackRange: [24, 40],
    health: 180,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/3uir7f.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 5000, minLevel: 25 },
  },
  {
    id: "nami_c_01",
    name: "Nami",
    title: "Cat burglar (Cocoyashi Village)",
    rank: "C",
    power: 45,
    attackRange: [8, 18],
    health: 95,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/n9uxge.jpg",
    evolutions: ["nami_b_02"],
  },
  {
    id: "nami_b_02",
    name: "Nami",
    title: "Navigator of the Straw Hat Pirates",
    rank: "B",
    power: 85,
    attackRange: [18, 34],
    health: 150,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/yi0eql.jpg",
    evolutions: ["nami_a_03"],
    isUpgrade: true,
    upgradeRequirements: { cost: 3000, minLevel: 18 },
  },
  {
    id: "nami_a_03",
    name: "Nami",
    title: "Navigator & Strategist",
    rank: "A",
    power: 170,
    attackRange: [30, 48],
    health: 210,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/bjloxa.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 9000, minLevel: 36 },
  },
  // User-requested additions
  {
    id: "buggy_b_01",
    name: "Buggy",
    title: "Buggy the Clown (Buggy Pirates)",
    rank: "B",
    power: 95,
    attackRange: [18, 34],
    health: 160,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/7ihpf3.jpg",
    evolutions: ["buggy_a_02"],
  },
  {
    id: "buggy_a_02",
    name: "Buggy",
    title: "Buggy the Clown (Captain)",
    rank: "A",
    power: 170,
    attackRange: [28, 50],
    health: 240,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/placeholder.jpg",
    evolutions: ["buggy_s_03"],
    isUpgrade: true,
    upgradeRequirements: { cost: 4000, minLevel: 25 },
  },
  {
    id: "buggy_s_03",
    name: "Buggy",
    title: "Buggy the Clown (Notorious Pirate)",
    rank: "S",
    power: 300,
    attackRange: [40, 70],
    health: 330,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/ncsz9e.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 12000, minLevel: 50 },
  },
  {
    id: "cabaji_c_01",
    name: "Cabaji",
    title: "Acrobat (Buggy Pirates)",
    rank: "C",
    power: 48,
    attackRange: [8, 20],
    health: 110,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/k4y1rj.jpg",
    evolutions: [],
  },
  {
    id: "mohji_c_01",
    name: "Mohji",
    title: "Beast Tamer (Buggy Crew)",
    rank: "C",
    power: 52,
    attackRange: [10, 22],
    health: 120,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/dp2f5f.jpg",
    evolutions: [],
  },
  {
    id: "richie_c_01",
    name: "Richie",
    title: "Minor pirate (East Blue)",
    rank: "C",
    power: 34,
    attackRange: [6, 14],
    health: 88,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/6xy44d.jpg",
    evolutions: [],
  },
  {
    id: "boodle_c_01",
    name: "Boodle",
    title: "Minor pirate (East Blue)",
    rank: "C",
    power: 36,
    attackRange: [6, 16],
    health: 92,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/p5z96g.webp",
    evolutions: [],
  },
  {
    id: "chouchou_c_01",
    name: "Chouchou",
    title: "Minor character (East Blue)",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 80,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/fg7kje.webp",
    evolutions: [],
  },
  {
    id: "captainkuro_b_01",
    name: "Captain Kuro",
    title: "Captain of the Kuro Pirates",
    rank: "B",
    power: 110,
    attackRange: [20, 36],
    health: 170,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/5mm1sl.webp",
    evolutions: [],
  },
  {
    id: "jango_b_01",
    name: "Jango",
    title: "Hypnotist (Black Cat Pirates)",
    rank: "B",
    power: 100,
    attackRange: [18, 34],
    health: 160,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/k81taa.webp",
    evolutions: [],
  },
  {
    id: "ussop_c_01",
    name: "Usopp",
    title: "Sniper (Syrup Village)",
    rank: "C",
    power: 50,
    attackRange: [10, 24],
    health: 120,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/sipqbo.gif",
    evolutions: ["usopp_b_02"],
  },
  {
    id: "usopp_b_02",
    name: "Usopp",
    title: "Sniper of the Straw Hat Pirates",
    rank: "B",
    power: 115,
    attackRange: [20, 36],
    health: 170,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/g5fet0.jpg",
    evolutions: ["usopp_a_03"],
    isUpgrade: true,
    upgradeRequirements: { cost: 2500, minLevel: 18 },
  },
  {
    id: "usopp_a_03",
    name: "Usopp",
    title: "Sogeking / Brave Warrior",
    rank: "A",
    power: 200,
    attackRange: [30, 52],
    health: 240,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/3azibs.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 7500, minLevel: 36 },
  },
  {
    id: "kaya_c_01",
    name: "Kaya",
    title: "Heiress (Syrup Village)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 100,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/gv72ra.jpg",
    evolutions: [],
  },
  {
    id: "gaimon_c_01",
    name: "Gaimon",
    title: "Treasure-Seeking Sailor",
    rank: "C",
    power: 36,
    attackRange: [6, 14],
    health: 110,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/ki7eb5.jpg",
    evolutions: [],
  },
  {
    id: "draculemihawk_ur_01",
    name: "Dracule Mihawk",
    title: "Greatest Swordsman in the World",
    rank: "UR",
    power: 980,
    attackRange: [140, 180],
    health: 920,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/86rpqj.jpg",
    evolutions: [],
  },
  {
    id: "donkrieg_b_01",
    name: "Don Krieg",
    title: "Warlord of the Sea (Self-Proclaimed)",
    rank: "B",
    power: 120,
    attackRange: [22, 38],
    health: 180,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/i10n26.jpg",
    evolutions: [],
  },
  {
    id: "pearl_c_01",
    name: "Pearl",
    title: "Crewman (Don Krieg Fleet)",
    rank: "C",
    power: 34,
    attackRange: [6, 14],
    health: 90,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/xr7f7k.jpg",
    evolutions: [],
  },
  {
    id: "gin_c_01",
    name: "Gin",
    title: "Crewman (Baroque Works / East Blue variants)",
    rank: "C",
    power: 44,
    attackRange: [8, 18],
    health: 100,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/79jy4k.jpg",
    evolutions: [],
  },
  {
    id: "sanji_b_01",
    name: "Sanji",
    title: "Cook of the Straw Hat Pirates",
    rank: "B",
    power: 130,
    attackRange: [22, 38],
    health: 180,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/ez22il.jpg",
    evolutions: ["sanji_a_01"],
  },
  {
    id: "sanji_a_01",
    name: "Sanji",
    title: "Black Leg (Experienced Chef)",
    rank: "A",
    power: 220,
    attackRange: [30, 54],
    health: 260,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/4clrqb.jpg",
    evolutions: ["sanji_s_01"],
    isUpgrade: true,
    upgradeRequirements: { cost: 7000, minLevel: 36 },
  },
  {
    id: "sanji_s_01",
    name: "Sanji",
    title: "Black Leg (Elite)",
    rank: "S",
    power: 360,
    attackRange: [50, 90],
    health: 380,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/placeholder.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 20000, minLevel: 60 },
  },
  {
    id: "redlegzeff_b_01",
    name: "Red-Leg Zeff",
    title: "Head Chef (Baratie)",
    rank: "B",
    power: 115,
    attackRange: [20, 36],
    health: 175,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/sfxltx.jpg",
    evolutions: [],
  },
  {
    id: "fullbody_b_01",
    name: "Fullbody",
    title: "Marine Officer (Syrup Village)",
    rank: "B",
    power: 98,
    attackRange: [18, 34],
    health: 160,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/48imho.jpg",
    evolutions: [],
  },
  {
    id: "patty_c_01",
    name: "Patty",
    title: "Baratie Crew (Waitress)",
    rank: "C",
    power: 36,
    attackRange: [6, 14],
    health: 100,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/vkbj2c.jpg",
    evolutions: [],
  },
  {
    id: "carny_c_01",
    name: "Carny",
    title: "Baratie Crew (Deckhand)",
    rank: "C",
    power: 32,
    attackRange: [5, 12],
    health: 92,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/qrw6dc.jpg",
    evolutions: [],
  },
  {
    id: "arlong_a_01",
    name: "Arlong",
    title: "Captain of the Arlong Pirates",
    rank: "A",
    power: 210,
    attackRange: [36, 60],
    health: 300,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/v8enk9.jpg",
    evolutions: [],
  },
  {
    id: "kuroobi_b_01",
    name: "Kuroobi",
    title: "Officer (Arlong Pirates)",
    rank: "B",
    power: 110,
    attackRange: [20, 36],
    health: 170,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/4idzyy.jpg",
    evolutions: [],
  },
  {
    id: "hatchan_b_01",
    name: "Hatchan",
    title: "Octopus Fish-Man (Arlong Crew)",
    rank: "B",
    power: 125,
    attackRange: [22, 40],
    health: 190,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/ev0gga.jpg",
    evolutions: [],
  },
  {
    id: "nezumi_c_01",
    name: "Nezumi",
    title: "Minor character (East Blue)",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 84,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/ptlrl9.jpg",
    evolutions: [],
  },
  {
    id: "genzo_c_01",
    name: "Genzo",
    title: "Town Guard (Syrup Village / Loguetown variants)",
    rank: "C",
    power: 40,
    attackRange: [6, 16],
    health: 100,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/wvnf6c.jpg",
    evolutions: [],
  },
  {
    id: "nojiko_c_01",
    name: "Nojiko",
    title: "Nami's sister (Cocoyashi Village)",
    rank: "C",
    power: 34,
    attackRange: [6, 14],
    health: 98,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/r3izm9.jpg",
    evolutions: [],
  },
  {
    id: "smoker_a_01",
    name: "Smoker",
    title: "White Chase (Marine)",
    rank: "A",
    power: 240,
    attackRange: [32, 56],
    health: 280,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/tjkgg5.jpg",
    evolutions: ["smoker_s_01"],
    isUpgrade: true,
    upgradeRequirements: { cost: 9000, minLevel: 38 },
  },
  {
    id: "smoker_s_01",
    name: "Smoker",
    title: "Admiral-Class Marine (Elite)",
    rank: "S",
    power: 420,
    attackRange: [50, 90],
    health: 420,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/xulj6c.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 22000, minLevel: 65 },
  },
  {
    id: "tashigi_b_01",
    name: "Tashigi",
    title: "Marine Officer (Early)",
    rank: "B",
    power: 105,
    attackRange: [18, 34],
    health: 162,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/s5beh4.jpg",
    evolutions: ["tashigi_a_01"],
  },
  {
    id: "tashigi_a_01",
    name: "Tashigi",
    title: "Marine Officer (Skilled Swordswoman)",
    rank: "A",
    power: 195,
    attackRange: [28, 48],
    health: 230,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/sak50u.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 6800, minLevel: 34 },
  },
  {
    id: "monkeyddragon_ur_01",
    name: "Monkey D. Dragon",
    title: "Leader of the Revolutionary Army",
    rank: "UR",
    power: 1100,
    attackRange: [150, 200],
    health: 980,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/o5rhb8.jpg",
    evolutions: [],
  },
  {
    id: "ipponmatsu_c_01",
    name: "Ipponmatsu",
    title: "Fisherman (Foosha Village)",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 88,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/grq2se.jpg",
    evolutions: [],
  },
  {
    id: "yu_c_01",
    name: "Yu",
    title: "Minor character (East Blue)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 82,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/7z8bah.webp",
    evolutions: [],
  },
  {
    id: "sapi_c_01",
    name: "Sapi",
    title: "Minor character (East Blue)",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 76,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/rvpde0.webp",
    evolutions: [],
  },
  // More user-requested minor/animal cards
  {
    id: "rika_c_01",
    name: "Rika",
    title: "Village girl (Minor)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/3lrtbe.webp",
    evolutions: [],
  },
  {
    id: "ririka_c_01",
    name: "Ririka",
    title: "Village girl (Minor)",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 80,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/azd1gb.webp",
    evolutions: [],
  },
  {
    id: "ukkari_c_01",
    name: "Ukkari",
    title: "Townsperson (Minor)",
    rank: "C",
    power: 24,
    attackRange: [3, 10],
    health: 78,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/xd6gx4.webp",
    evolutions: [],
  },
  {
    id: "rokkaku_c_01",
    name: "Rokkaku",
    title: "Local guard (Minor)",
    rank: "C",
    power: 34,
    attackRange: [6, 14],
    health: 96,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/n7xrnm.webp",
    evolutions: [],
  },
  {
    id: "ripper_c_01",
    name: "Ripper",
    title: "Thug (Minor)",
    rank: "C",
    power: 36,
    attackRange: [6, 16],
    health: 98,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/41cavp.webp",
    evolutions: [],
  },
  {
    id: "soro_c_01",
    name: "Soro",
    title: "Minor swordsman",
    rank: "C",
    power: 44,
    attackRange: [8, 18],
    health: 110,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/jv8td8.webp",
    evolutions: [],
  },
  {
    id: "marinex_c_01",
    name: "Marine X",
    title: "random marine",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/7p69bl.webp",
    evolutions: [],
  },
  {
    id: "sada_c_01",
    name: "Sada",
    title: "Local villager",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 78,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/49e50f.webp",
    evolutions: [],
  },
  {
    id: "koushiru_b_01",
    name: "Koushiru",
    title: "Experienced fighter",
    rank: "B",
    power: 120,
    attackRange: [20, 36],
    health: 170,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/a4s5kx.webp",
    evolutions: [],
  },
  {
    id: "kuina_b_01",
    name: "Kuina",
    title: "Aspiring swordswoman",
    rank: "B",
    power: 140,
    attackRange: [22, 38],
    health: 180,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/ge8y9x.webp",
    evolutions: [],
  },
  {
    id: "kouzaburou_b_01",
    name: "Kouzaburou",
    title: "Village elder (Minor)",
    rank: "B",
    power: 28,
    attackRange: [4, 12],
    health: 88,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/kuvu3p.webp",
    evolutions: [],
  },
  {
    id: "himari_c_01",
    name: "Himari",
    title: "Young villager",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 80,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/lvt93d.webp",
    evolutions: [],
  },
  {
    id: "saga_c_01",
    name: "Saga",
    title: "Minor mercenary",
    rank: "C",
    power: 38,
    attackRange: [6, 16],
    health: 100,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/jui7he.webp",
    evolutions: [],
  },
  {
    id: "poro_c_01",
    name: "Poro",
    title: "Dockworker (Minor)",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 88,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/w9al2n.webp",
    evolutions: [],
  },
  {
    id: "hocker_c_01",
    name: "Hocker",
    title: "Street tough",
    rank: "C",
    power: 36,
    attackRange: [6, 16],
    health: 96,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/y5c05w.webp",
    evolutions: [],
  },
  {
    id: "sarfunkel_c_01",
    name: "Sarfunkel",
    title: "Odd jobber (Minor)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/blz2zk.webp",
    evolutions: [],
  },
  {
    id: "cocox_c_01",
    name: "Coco X",
    title: "Carnival performer",
    rank: "C",
    power: 34,
    attackRange: [6, 14],
    health: 94,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/m5bfq4.webp",
    evolutions: [],
  },
  {
    id: "usagihebi_c_01",
    name: "Usagihebi",
    title: "Beast (Rabbit-Serpent hybrid)",
    rank: "C",
    power: 40,
    attackRange: [7, 16],
    health: 110,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/ecagnd.webp",
    evolutions: [],
  },
  {
    id: "lionbuta_c_01",
    name: "Lionbuta",
    title: "Beast (Lion-Pig)",
    rank: "C",
    power: 46,
    attackRange: [8, 18],
    health: 120,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/arkd42.webp",
    evolutions: [],
  },
  {
    id: "kirinkodanuki_c_01",
    name: "Kirinkodanuki",
    title: "Beast (Mythical hybrid)",
    rank: "C",
    power: 44,
    attackRange: [8, 18],
    health: 116,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/g5762z.webp",
    evolutions: [],
  },
  {
    id: "kabagorilla_c_01",
    name: "Kaba-Gorilla",
    title: "Beast (Hippo-Gorilla hybrid)",
    rank: "C",
    power: 48,
    attackRange: [9, 18],
    health: 128,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/f4beoj.webp",
    evolutions: [],
  },
  {
    id: "kamonohitsuji_c_01",
    name: "Kamonohitsuji",
    title: "Sheep-headed beast",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 78,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/w2htv4.webp",
    evolutions: [],
  },
  {
    id: "saikangaroo_c_01",
    name: "Saikan-Garoo",
    title: "Beast (Kangaroo hybrid)",
    rank: "C",
    power: 38,
    attackRange: [6, 14],
    health: 102,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/7j5vx8.webp",
    evolutions: [],
  },
  {
    id: "banchina_c_01",
    name: "Banchina",
    title: "Market trader",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/1jo5vk.webp",
    evolutions: [],
  },
  {
    id: "ninjin_c_01",
    name: "Ninjin",
    title: "Market produce (NPC)",
    rank: "C",
    power: 6,
    attackRange: [1, 4],
    health: 24,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/5zon73.webp",
    evolutions: [],
  },
  {
    id: "tamanegi_c_01",
    name: "Tamanegi",
    title: "Market produce (NPC)",
    rank: "C",
    power: 6,
    attackRange: [1, 4],
    health: 24,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/j6aghh.webp",
    evolutions: [],
  },
  {
    id: "piiman_c_01",
    name: "Piiman",
    title: "Market produce (NPC)",
    rank: "C",
    power: 6,
    attackRange: [1, 4],
    health: 24,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/placeholder.jpg",
    evolutions: [],
  },
  {
    id: "mornin_c_01",
    name: "Mornin",
    title: "Street vendor",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 80,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/84r4s3.webp",
    evolutions: [],
  },
  {
    id: "luigia_c_01",
    name: "Luigia",
    title: "Mansion maid (Minor)",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 88,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/36gbby.webp",
    evolutions: [],
  },
  {
    id: "mansionsguard_c_01",
    name: "Mansion's Guard",
    title: "Estate guard",
    rank: "C",
    power: 40,
    attackRange: [8, 18],
    health: 110,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/yezy55.webp",
    evolutions: [],
  },
  {
    id: "mansionsguard_c_02",
    name: "Mansion's Guard",
    title: "Estate guard (alternate)",
    rank: "C",
    power: 42,
    attackRange: [8, 18],
    health: 112,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/yezy55.webp",
    evolutions: [],
  },
  // Additional user-requested cards
  {
    id: "kingsterry_c_01",
    name: "Kingsterry",
    title: "Royal figure (Goa Kingdom)",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 88,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/yymvei.webp",
    evolutions: [],
  },
  {
    id: "queensarie_c_01",
    name: "Queen Sarie",
    title: "Noble (Goa Kingdom)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/smnu9v.webp",
    evolutions: [],
  },
  {
    id: "kingofgoa_c_01",
    name: "King of Goa",
    title: "Monarch (Goa Kingdom)",
    rank: "C",
    power: 36,
    attackRange: [6, 14],
    health: 100,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/ytoh2w.webp",
    evolutions: [],
  },
  {
    id: "outlook3_c_01",
    name: "Outlook 3",
    title: "Minor crewman (named)",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 80,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/placeholder.jpg",
    evolutions: [],
  },
  {
    id: "didit_c_01",
    name: "Didit",
    title: "Fisherman (Foosha Village)",
    rank: "C",
    power: 32,
    attackRange: [6, 12],
    health: 90,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/iaw48k.webp",
    evolutions: [],
  },
  {
    id: "ahhodessunen_c_01",
    name: "Ahhodes Sunen",
    title: "Island native (Minor)",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 88,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/2js3ks.webp",
    evolutions: [],
  },
  {
    id: "ahhozurako_c_01",
    name: "Ahho Zurako",
    title: "Island native (Minor)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 84,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/7uohkt.webp",
    evolutions: [],
  },
  {
    id: "sabo_c_01",
    name: "Sabo",
    title: "Revolutionary (Child)",
    rank: "C",
    power: 90,
    attackRange: [16, 30],
    health: 150,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/2410ln.webp",
    evolutions: ["sabo_s_01"],
  },
  {
    id: "sabo_s_01",
    name: "Sabo",
    title: "Chief of Staff (Revolutionary)",
    rank: "S",
    power: 360,
    attackRange: [48, 86],
    health: 420,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/tx4q1m.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 22000, minLevel: 60 },
  },
  {
    id: "gyoru_c_01",
    name: "Gyoru",
    title: "Maritime worker (Minor)",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 78,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/4qhte5.webp",
    evolutions: [],
  },
  {
    id: "chicken_c_01",
    name: "Chicken",
    title: "Farm animal (NPC)",
    rank: "C",
    power: 10,
    attackRange: [1, 4],
    health: 30,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/xk7u3d.webp",
    evolutions: [],
  },
  {
    id: "makinoschild_c_01",
    name: "Makino's Child",
    title: "Villager (Foosha Village)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/56iyfh.webp",
    evolutions: [],
  },
  {
    id: "monkeydgarp_ss_01",
    name: "Monkey D. Garp",
    title: "Hero of the Marines (Old)",
    rank: "SS",
    power: 600,
    attackRange: [80, 120],
    health: 700,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/dvemqd.webp",
    evolutions: ["monkeydgarp_ur_02"],
    isUpgrade: true,
    upgradeRequirements: { cost: 30000, minLevel: 60 },
  },
  {
    id: "monkeydgarp_ur_02",
    name: "Monkey D. Garp",
    title: "Marine Hero (Prime)",
    rank: "UR",
    power: 1100,
    attackRange: [140, 200],
    health: 990,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/v3hkby.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 90000, minLevel: 100 },
  },
  {
    id: "portgacdace_c_01",
    name: "Portga C. Dace",
    title: "Marine (Minor)",
    rank: "C",
    power: 38,
    attackRange: [6, 14],
    health: 98,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/91lisa.jpg",
    evolutions: ["portgacedace_s_01"],
  },
  {
    id: "portgacedace_s_01",
    name: "Portga C. Dace",
    title: "Seasoned Officer",
    rank: "S",
    power: 320,
    attackRange: [50, 88],
    health: 380,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/zqhyvx.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 20000, minLevel: 60 },
  },
  {
    id: "curlydadan_c_01",
    name: "Curly Dadan",
    title: "Mountain bandit (Adoptive parent)",
    rank: "C",
    power: 42,
    attackRange: [8, 18],
    health: 110,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/4b8wt3.webp",
    evolutions: [],
  },
  {
    id: "dogra_c_01",
    name: "Dogra",
    title: "Forest villager (Minor)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/x8ndw2.webp",
    evolutions: [],
  },
  {
    id: "magra_c_01",
    name: "Magra",
    title: "Red-haired crewman (Minor)",
    rank: "C",
    power: 32,
    attackRange: [6, 14],
    health: 92,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/a3xpgk.webp",
    evolutions: [],
  },
  {
    id: "minatomo_c_01",
    name: "Minatomo",
    title: "Island villager",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 78,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/cqg9mv.webp",
    evolutions: [],
  },
  {
    id: "lordofthecoast_b_01",
    name: "Lord of the Coast",
    title: "Sea ruler (Legendary title)",
    rank: "B",
    power: 140,
    attackRange: [24, 42],
    health: 190,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/8nzeq9.webp",
    evolutions: [],
  },
  {
    id: "naguri_c_01",
    name: "Naguri",
    title: "Local fisherman",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 88,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/x6lsk5.webp",
    evolutions: [],
  },
  {
    id: "pochi_c_01",
    name: "Pochi",
    title: "Pet dog (NPC)",
    rank: "C",
    power: 12,
    attackRange: [1, 4],
    health: 34,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/0y6dzn.webp",
    evolutions: [],
  },
  {
    id: "gillian_c_01",
    name: "Gillian",
    title: "Port worker (Minor)",
    rank: "C",
    power: 34,
    attackRange: [6, 14],
    health: 92,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/3g8e89.webp",
    evolutions: [],
  },
  // Bulk additions requested by user (bellmere...hardy)
  {
    id: "bellmere_b_01",
    name: "Bell-mère",
    title: "Adoptive mother of Nami (Cocoyashi Village)",
    rank: "B",
    power: 130,
    attackRange: [22, 38],
    health: 200,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/jo9vq1.webp",
    evolutions: [],
  },
  {
    id: "nojiko_b_01",
    name: "Nojiko",
    title: "Nami's sister (Cocoyashi Village)",
    rank: "B",
    power: 110,
    attackRange: [20, 34],
    health: 170,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/0gfj06.webp",
    evolutions: [],
  },
  {
    id: "genzo_b_01",
    name: "Genzo",
    title: "Town guard (Loguetown/Syrup Village)",
    rank: "B",
    power: 108,
    attackRange: [18, 36],
    health: 168,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/boye4w.webp",
    evolutions: [],
  },
  {
    id: "nako_c_01",
    name: "Nako",
    title: "Village girl (Minor)",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 80,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/wqdazz.webp",
    evolutions: [],
  },
  {
    id: "chabo_c_01",
    name: "Chabo",
    title: "Street urchin (Sabaody/Childhood)",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/mrfud5.webp",
    evolutions: [],
  },
  {
    id: "mummymee_c_01",
    name: "Mummy Mee",
    title: "Minor townsperson",
    rank: "C",
    power: 24,
    attackRange: [3, 10],
    health: 74,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/9j0bv4.webp",
    evolutions: [],
  },
  {
    id: "daddydee_c_01",
    name: "Daddy Dee",
    title: "Minor townsperson",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 78,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/rxzgit.webp",
    evolutions: [],
  },
  {
    id: "johnny_b_01",
    name: "Johnny",
    title: "Friend of Zoro (Shimotsuki Village)",
    rank: "B",
    power: 115,
    attackRange: [20, 36],
    health: 172,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/s5d98s.webp",
    evolutions: [],
  },
  {
    id: "yoasaku_b_01",
    name: "Yoasaku",
    title: "Town mayor/guard (Loguetown)",
    rank: "B",
    power: 105,
    attackRange: [18, 32],
    health: 160,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/jrnxqx.webp",
    evolutions: [],
  },
  {
    id: "sam_c_01",
    name: "Sam",
    title: "Dockhand (Minor)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/tru671.webp",
    evolutions: [],
  },
  {
    id: "goldroger_ss_01",
    name: "Gol D. Roger",
    title: "Pirate King (Legend)",
    rank: "SS",
    power: 900,
    attackRange: [120, 160],
    health: 950,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/9nu1eb.webp",
    evolutions: ["goldroger_ur_01"],
    isUpgrade: true,
    upgradeRequirements: { cost: 40000, minLevel: 70 },
  },
  {
    id: "goldroger_ur_01",
    name: "Gol D. Roger",
    title: "Pirate King (Prime)",
    rank: "UR",
    power: 1800,
    attackRange: [180, 260],
    health: 1600,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/j02my2.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 150000, minLevel: 120 },
  },
  {
    id: "ipponume_c_01",
    name: "Ipponume",
    title: "Villager (Minor)",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 80,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/49cy4x.webp",
    evolutions: [],
  },
  {
    id: "hanger_c_01",
    name: "Hanger",
    title: "Cargo handler (Minor)",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/c8j66i.webp",
    evolutions: [],
  },
  {
    id: "packy_c_01",
    name: "Packy",
    title: "Deckhand (Minor)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 84,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/xlhpjl.webp",
    evolutions: [],
  },
  {
    id: "mashikaku_c_01",
    name: "Mashikaku",
    title: "Minor thug",
    rank: "C",
    power: 34,
    attackRange: [6, 14],
    health: 94,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/d99ex1.webp",
    evolutions: [],
  },
  {
    id: "ed_c_01",
    name: "Ed",
    title: "Minor character (East Blue)",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 80,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/0r0029.webp",
    evolutions: [],
  },
  {
    id: "raoul_c_01",
    name: "Raoul",
    title: "Sailor (Minor)",
    rank: "C",
    power: 32,
    attackRange: [6, 14],
    health: 92,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/8e00cb.webp",
    evolutions: [],
  },
  {
    id: "daddymasteron_c_01",
    name: "Daddy Masteron",
    title: "Circus master (Minor)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/igezg8.webp",
    evolutions: [],
  },
  {
    id: "carol_c_01",
    name: "Carol",
    title: "Minor character",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 80,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/nqsc0t.webp",
    evolutions: [],
  },
  {
    id: "eccoli_c_01",
    name: "Eccoli",
    title: "Minor sailor",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 86,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/rtnmj6.webp",
    evolutions: [],
  },
  {
    id: "dias_c_01",
    name: "Dias",
    title: "Townsperson (Minor)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 84,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/1guoiz.webp",
    evolutions: [],
  },
  {
    id: "kingfurrari_c_01",
    name: "King Furrari",
    title: "Circus performer (Minor)",
    rank: "C",
    power: 34,
    attackRange: [6, 14],
    health: 94,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/azvnyr.webp",
    evolutions: [],
  },
  {
    id: "princetritobu_c_01",
    name: "Prince Tritobu",
    title: "Royalty (Minor)",
    rank: "C",
    power: 36,
    attackRange: [6, 16],
    health: 96,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/udiphx.webp",
    evolutions: [],
  },
  {
    id: "nyornyonyrmani_c_01",
    name: "Nyorn Yonyrmani",
    title: "Court official (Minor)",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 88,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/placeholder.jpg",
    evolutions: [],
  },
  {
    id: "hamu_c_01",
    name: "Hamu",
    title: "Minor villager",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 80,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/b0iri3.webp",
    evolutions: [],
  },
  {
    id: "meroie_c_01",
    name: "Meroie",
    title: "Fisherwoman (Minor)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/8va4m8.webp",
    evolutions: [],
  },
  {
    id: "joke_a_01",
    name: "Joke",
    title: "Comedian (Named NPC)",
    rank: "A",
    power: 150,
    attackRange: [26, 44],
    health: 210,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/9ann7a.webp",
    evolutions: [],
  },
  {
    id: "apis_c_01",
    name: "Apis",
    title: "Minor character",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/rlfe5e.webp",
    evolutions: [],
  },
  {
    id: "bokuden_c_01",
    name: "Bokuden",
    title: "Martial artist (Minor)",
    rank: "C",
    power: 40,
    attackRange: [8, 18],
    health: 110,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/vqdxro.webp",
    evolutions: [],
  },
  {
    id: "ryu_c_01",
    name: "Ryu",
    title: "Swordsman (Minor)",
    rank: "C",
    power: 36,
    attackRange: [6, 16],
    health: 98,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/ozwyg0.webp",
    evolutions: [],
  },
  {
    id: "akisu_c_01",
    name: "Akisu",
    title: "Local merchant (Minor)",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 80,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/pmtidm.webp",
    evolutions: [],
  },
  {
    id: "umenonazawa_c_01",
    name: "Umeno Nazawa",
    title: "Villager (Minor)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/i32te2.webp",
    evolutions: [],
  },
  {
    id: "tsubaki_c_01",
    name: "Tsubaki",
    title: "Household helper (Minor)",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 80,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/6dfnvy.webp",
    evolutions: [],
  },
  {
    id: "taketonazawa_c_01",
    name: "Taketona Zawa",
    title: "Fisher (Minor)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/0abs6d.webp",
    evolutions: [],
  },
  {
    id: "pinky_c_01",
    name: "Pinky",
    title: "Performer (Minor)",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 80,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/8jh09g.webp",
    evolutions: [],
  },
  {
    id: "roxanne_c_01",
    name: "Roxanne",
    title: "Marina attendant (Minor)",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/ezx7sp.webp",
    evolutions: [],
  },
  {
    id: "moodie_c_01",
    name: "Moodie",
    title: "Minor crewman",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 84,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/37r74m.webp",
    evolutions: [],
  },
  {
    id: "motzel_c_01",
    name: "Motzel",
    title: "Minor thug",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 88,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/s7290k.webp",
    evolutions: [],
  },
  {
    id: "batchee_c_01",
    name: "Batchee",
    title: "insect",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 80,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/xeysup.webp",
    evolutions: [],
  },
  {
    id: "anjo_c_01",
    name: "Anjo",
    title: "Shipwright (Minor)",
    rank: "C",
    power: 32,
    attackRange: [6, 14],
    health: 92,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/vcelyw.webp",
    evolutions: [],
  },
  {
    id: "misscatherina_c_01",
    name: "Miss Catherina",
    title: "High-society (Minor)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/k7vjnd.webp",
    evolutions: [],
  },
  {
    id: "bonclay_a_01",
    name: "Bon Clay",
    title: "Okama Martial Artist (Mr. 2)",
    rank: "A",
    power: 260,
    attackRange: [40, 70],
    health: 320,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/ug0cer.webp",
    evolutions: [],
  },
  {
    id: "kumatetribe_c_01",
    name: "Kumate Tribe",
    title: "Tribe member (Minor)",
    rank: "C",
    power: 36,
    attackRange: [6, 14],
    health: 98,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/piev4m.webp",
    evolutions: [],
  },
  {
    id: "bandedessinee_c_01",
    name: "Ban dedessinée",
    title: "Storyteller (Minor)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/eqculz.webp",
    evolutions: [],
  },
  {
    id: "herring_c_01",
    name: "Herring",
    title: "Fishmonger (Minor)",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 80,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/ew3c3j.webp",
    evolutions: [],
  },
  {
    id: "medaka_c_01",
    name: "Medaka",
    title: "Fisher (Minor)",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 88,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/kl7o2j.webp",
    evolutions: [],
  },
  {
    id: "skid_c_01",
    name: "Skid",
    title: "Dockhand (Minor)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 84,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/owxcy9.webp",
    evolutions: [],
  },
  {
    id: "ganzo_c_01",
    name: "Ganzo",
    title: "Brawler (Minor)",
    rank: "C",
    power: 36,
    attackRange: [6, 16],
    health: 96,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/dg0jv3.webp",
    evolutions: [],
  },
  {
    id: "tobio_c_01",
    name: "Tobio",
    title: "Local youth (Minor)",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 80,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/lyyew6.webp",
    evolutions: [],
  },
  {
    id: "carmen_c_01",
    name: "Carmen",
    title: "Performer (Minor)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 84,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/foj0y4.webp",
    evolutions: [],
  },
  {
    id: "leo_c_01",
    name: "Leo",
    title: "Sailor (Minor)",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 88,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/5fmoax.webp",
    evolutions: [],
  },
  {
    id: "jose_c_01",
    name: "Jose",
    title: "Port worker (Minor)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 84,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/582qx3.webp",
    evolutions: [],
  },
  {
    id: "shutai_c_01",
    name: "Shutai",
    title: "Minor thug",
    rank: "C",
    power: 34,
    attackRange: [6, 14],
    health: 94,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/cmyobd.webp",
    evolutions: [],
  },
  {
    id: "eric_c_01",
    name: "Eric",
    title: "Street vendor (Minor)",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 80,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/9v0idi.webp",
    evolutions: [],
  },
  {
    id: "borodo_c_01",
    name: "Borodo",
    title: "Fisher (Minor)",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 88,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/m2h76h.webp",
    evolutions: [],
  },
  {
    id: "harry_c_01",
    name: "Harry",
    title: "Sailor (Minor)",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 80,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/sv7s87.webp",
    evolutions: [],
  },
  {
    id: "febre_c_01",
    name: "Febre",
    title: "Minor doctor/medic",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/i21qk2.webp",
    evolutions: [],
  },
  {
    id: "mendo_c_01",
    name: "Mendo",
    title: "Chef (Minor)",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 88,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/pchnxa.webp",
    evolutions: [],
  },
  {
    id: "savarin_c_01",
    name: "Savarin",
    title: "Patron (Minor)",
    rank: "C",
    power: 32,
    attackRange: [6, 14],
    health: 92,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/ynke9i.webp",
    evolutions: [],
  },
  {
    id: "ruibe_c_01",
    name: "Ruibe",
    title: "Circus assistant (Minor)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/j9pefs.webp",
    evolutions: [],
  },
  {
    id: "jodieandeliza_c_01",
    name: "Jodie & Eliza",
    title: "Twin performers (Minor)",
    rank: "C",
    power: 34,
    attackRange: [6, 14],
    health: 94,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/huyiqh.webp",
    evolutions: [],
  },
  {
    id: "bluedia_c_01",
    name: "Bluedia",
    title: "Performer (Minor)",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 80,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/gka81d.webp",
    evolutions: [],
  },
  {
    id: "meshi_c_01",
    name: "Meshi",
    title: "Cook's assistant (Minor)",
    rank: "C",
    power: 26,
    attackRange: [4, 10],
    health: 80,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/aiwmz4.webp",
    evolutions: [],
  },
  {
    id: "wier_c_01",
    name: "Wier",
    title: "Odd jobber (Minor)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 84,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/h8h05v.webp",
    evolutions: [],
  },
  {
    id: "lines_c_01",
    name: "Lines",
    title: "Dock marker (Minor)",
    rank: "C",
    power: 16,
    attackRange: [2, 6],
    health: 50,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/nyl2u5.webp",
    evolutions: [],
  },
  {
    id: "puddingpudding_c_01",
    name: "Pudding Pudding",
    title: "Dessert stand (NPC)",
    rank: "C",
    power: 6,
    attackRange: [1, 4],
    health: 24,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/yvl0nd.webp",
    evolutions: [],
  },
  {
    id: "kaku_a_01",
    name: "Kaku",
    title: "CP9 Agent (Human Form)",
    rank: "A",
    power: 220,
    attackRange: [30, 52],
    health: 260,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/ooz77p.webp",
    evolutions: ["kaku_s_02"],
    isUpgrade: true,
    upgradeRequirements: { cost: 8000, minLevel: 36 },
  },
  {
    id: "kaku_s_02",
    name: "Kaku",
    title: "CP9 Agent (Ox-Ox Fruit - Soru)",
    rank: "S",
    power: 420,
    attackRange: [50, 90],
    health: 420,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/jifkgj.jpg",
    evolutions: [],
    isUpgrade: true,
    upgradeRequirements: { cost: 22000, minLevel: 65 },
  },
  {
    id: "nelsonroyal_c_01",
    name: "Nelson Royal",
    title: "Minor noble",
    rank: "C",
    power: 30,
    attackRange: [5, 12],
    health: 86,
    type: "Support",
    ability: null,
    image: "https://files.catbox.moe/y8soz3.webp",
    evolutions: [],
  },
  {
    id: "hardy_c_01",
    name: "Hardy",
    title: "Sailor (Minor)",
    rank: "C",
    power: 28,
    attackRange: [4, 12],
    health: 84,
    type: "Attack",
    ability: null,
    image: "https://files.catbox.moe/o1rgs3.webp",
    evolutions: [],
  },
];

export function getCardById(id) {
  return cards.find((c) => c.id === id) || null;
}

// Probability-driven random card selection
// probabilities is an object with rank keys -> percentage (summing to 100)
export function getRandomCardByProbability(probabilities = { C: 50, B: 30, A: 15, S: 3, ITEM: 2 }) {
  const entries = Object.entries(probabilities);
  const rnd = Math.random() * 100;
  let acc = 0;
  let chosenRank = null;
  for (const [rank, pct] of entries) {
    acc += pct;
    if (rnd <= acc) {
      chosenRank = rank;
      break;
    }
  }
  if (!chosenRank || chosenRank === "ITEM") chosenRank = "C";
  // exclude upgraded versions from pulls
  const pool = cards.filter((c) => !c.isUpgrade && c.rank && c.rank.toUpperCase() === String(chosenRank).toUpperCase());
  if (pool.length > 0) return pool[Math.floor(Math.random() * pool.length)];
  // fallback should also exclude upgrade variants so evolved cards are never pullable
  const fallback = cards.filter((c) => !c.isUpgrade && c.rank && c.rank.toUpperCase() !== "ITEM");
  if (fallback.length > 0) return fallback[Math.floor(Math.random() * fallback.length)];
  const nonUpgrade = cards.filter((c) => !c.isUpgrade);
  return nonUpgrade.length > 0 ? nonUpgrade[Math.floor(Math.random() * nonUpgrade.length)] : cards[Math.floor(Math.random() * cards.length)];
}

export function getRankInfo(rank) {
  return RANKS[String(rank).toUpperCase()] || null;
}
